<?php
/**
 * "Continue with Google" — the provider half.
 *
 * WHAT THIS DOES AND, MORE IMPORTANTLY, WHAT IT DOES NOT
 * It signs a student in. That is all it does. There is no student portal on the
 * other side of it: a successful login sets a session and lands on account.php,
 * which says who you are and offers a sign-out. That is deliberate — the same
 * rule the login page has always carried, written down in CLAUDE.md as "a
 * message is not a login", applies in reverse here. A login that leads nowhere
 * is honest about leading nowhere; a login that pretends to unlock a portal
 * that does not exist is not.
 *
 * WHY THE OFFICE TOOL IS NOT REACHABLE THIS WAY
 * mpc_google_link_user() refuses to attach a Google identity to an account whose
 * role is staff or admin, and refuses to sign one in. Staff keep passwords.
 *
 * The reason is worth stating because the refusal looks like an inconvenience
 * until you follow it through: admin/ writes to an append-only money ledger. If
 * a staff member's account could be entered with Google, then the security of
 * the ledger is the security of that person's Gmail — its password, its
 * recovery flow, its session on a shared office machine, and Google's own
 * account-takeover surface. None of those are things this project can see or
 * audit. A forged payment cannot be deleted and is indistinguishable from a
 * real one (lib/auth.php), so the account that can write one should be reachable
 * only through a credential this system fully controls.
 *
 * WHAT IS VERIFIED, AND WHAT IS TRUSTED
 * The ID token is NOT signature-checked here, and that is not an oversight. It
 * is fetched by this server directly from Google's token endpoint over TLS, in
 * a back channel the browser never touches; Google's own documentation says a
 * token obtained that way may be used without verifying the signature, because
 * TLS already establishes who sent it. What IS checked is everything that
 * remains attacker-controllable even so: issuer, audience, expiry, and the
 * nonce that ties the token to this browser's login attempt.
 *
 * If this ever starts accepting an ID token from anywhere else — a JavaScript
 * sign-in button posting one, say — that reasoning collapses and full JWKS
 * signature verification becomes mandatory. Hence mpc_google_claims_from_code()
 * takes a code, never a token: the shape of the function is what keeps the
 * shortcut honest.
 */

declare(strict_types=1);

require_once __DIR__ . '/db.php';

const MPC_GOOGLE_AUTH_URL  = 'https://accounts.google.com/o/oauth2/v2/auth';
const MPC_GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token';

/** Google's two accepted `iss` values. Both are current; which one arrives is
 *  not something to depend on. */
const MPC_GOOGLE_ISSUERS = ['https://accounts.google.com', 'accounts.google.com'];

/** Clock skew allowed when checking `exp`. A shared host's clock drifts, and a
 *  student rejected because the server is 40 seconds fast has no way to know
 *  that is what happened. */
const MPC_GOOGLE_LEEWAY_SECONDS = 120;


/**
 * The Google block from the config file, or null if it is not set up.
 *
 * Null rather than an exception, because "not configured" is a normal state
 * here: local development and any deployment that has not registered an OAuth
 * client should show the button as unavailable rather than break the page. The
 * endpoints turn this into a plain message; see api/auth/google/start.php.
 *
 * @return array{client_id:string,client_secret:string,redirect_uri:string}|null
 */
function mpc_google_config(): ?array
{
    static $cfg = false;
    if ($cfg !== false) {
        return $cfg;
    }

    $all = require mpc_config_path();
    $g   = $all['google'] ?? null;

    if (! is_array($g)) {
        return $cfg = null;
    }

    foreach (['client_id', 'client_secret', 'redirect_uri'] as $key) {
        if (empty($g[$key]) || ! is_string($g[$key])) {
            return $cfg = null;
        }
    }

    return $cfg = [
        'client_id'     => $g['client_id'],
        'client_secret' => $g['client_secret'],
        'redirect_uri'  => $g['redirect_uri'],
    ];
}

/** Whether Google sign-in is usable on this deployment. */
function mpc_google_configured(): bool
{
    return mpc_google_config() !== null;
}

/**
 * Where to send the browser to start the flow.
 *
 * `state` is the CSRF defence for the callback and `nonce` ties the returned ID
 * token to this attempt. Both are generated by the caller and kept in the
 * session, because both are only worth anything if the value that comes back is
 * compared against one this browser was actually given.
 */
function mpc_google_auth_url(string $state, string $nonce): string
{
    $cfg = mpc_google_config();
    if ($cfg === null) {
        throw new RuntimeException('Google sign-in is not configured.');
    }

    return MPC_GOOGLE_AUTH_URL . '?' . http_build_query([
        'client_id'     => $cfg['client_id'],
        'redirect_uri'  => $cfg['redirect_uri'],
        'response_type' => 'code',

        // Exactly what is needed to know who signed in, and nothing more. Every
        // extra scope is a longer consent screen and more data this project
        // would then be holding without a use for it.
        'scope'         => 'openid email profile',

        'state'         => $state,
        'nonce'         => $nonce,

        // Ask for an account chooser every time. Without it, a student on a
        // shared machine at the institute is silently signed in as whoever used
        // the browser last — and on a shared machine that is the common case,
        // not the edge case.
        'prompt'        => 'select_account',
    ]);
}

/**
 * Swaps the one-time code for the ID token's claims.
 *
 * @return array{sub:string,email:?string,email_verified:bool,name:?string,picture:?string}
 * @throws RuntimeException with a message safe to log, never to print raw
 */
function mpc_google_claims_from_code(string $code, string $expectedNonce): array
{
    $cfg = mpc_google_config();
    if ($cfg === null) {
        throw new RuntimeException('Google sign-in is not configured.');
    }

    $body = mpc_google_post(MPC_GOOGLE_TOKEN_URL, [
        'code'          => $code,
        'client_id'     => $cfg['client_id'],
        'client_secret' => $cfg['client_secret'],
        'redirect_uri'  => $cfg['redirect_uri'],
        'grant_type'    => 'authorization_code',
    ]);

    $token = json_decode($body, true);
    if (! is_array($token) || empty($token['id_token']) || ! is_string($token['id_token'])) {
        throw new RuntimeException('Google token response carried no id_token.');
    }

    return mpc_google_read_id_token($token['id_token'], $cfg['client_id'], $expectedNonce);
}

/**
 * Reads and checks an ID token that arrived over the back channel.
 *
 * See the header for why the signature is not checked and why that is only safe
 * for a token fetched this way.
 *
 * @return array{sub:string,email:?string,email_verified:bool,name:?string,picture:?string}
 */
function mpc_google_read_id_token(string $jwt, string $clientId, string $expectedNonce): array
{
    $parts = explode('.', $jwt);
    if (count($parts) !== 3) {
        throw new RuntimeException('Malformed id_token.');
    }

    $claims = json_decode(mpc_base64url_decode($parts[1]), true);
    if (! is_array($claims)) {
        throw new RuntimeException('Unreadable id_token payload.');
    }

    if (! in_array((string) ($claims['iss'] ?? ''), MPC_GOOGLE_ISSUERS, true)) {
        throw new RuntimeException('id_token issuer is not Google.');
    }

    // The audience check is what stops an ID token minted for a DIFFERENT
    // Google application from being replayed here. Without it, anyone with
    // their own OAuth client could hand us a perfectly valid Google token for
    // their app and be signed in as the user it names.
    if (! hash_equals($clientId, (string) ($claims['aud'] ?? ''))) {
        throw new RuntimeException('id_token was issued for another application.');
    }

    if (((int) ($claims['exp'] ?? 0)) + MPC_GOOGLE_LEEWAY_SECONDS < time()) {
        throw new RuntimeException('id_token has expired.');
    }

    if (! hash_equals($expectedNonce, (string) ($claims['nonce'] ?? ''))) {
        throw new RuntimeException('id_token nonce does not match this sign-in attempt.');
    }

    $sub = (string) ($claims['sub'] ?? '');
    if ($sub === '') {
        throw new RuntimeException('id_token carried no subject.');
    }

    return [
        'sub'   => $sub,
        'email' => isset($claims['email']) ? (string) $claims['email'] : null,

        // Google sends this as a real boolean or as the string "true" depending
        // on where it came from. Comparing loosely to true would also accept
        // the string "false", which is exactly backwards.
        'email_verified' => ($claims['email_verified'] ?? false) === true
                         || ($claims['email_verified'] ?? '') === 'true',

        'name'    => isset($claims['name']) ? (string) $claims['name'] : null,
        'picture' => isset($claims['picture']) ? (string) $claims['picture'] : null,
    ];
}

/** base64url, which is base64 with two characters swapped and the padding
 *  dropped. str_pad puts the padding back; PHP's decoder wants it. */
function mpc_base64url_decode(string $s): string
{
    $s = strtr($s, '-_', '+/');

    return base64_decode(str_pad($s, (int) (ceil(strlen($s) / 4) * 4), '='), true) ?: '';
}

/**
 * One POST to Google, with the failure modes made loud.
 *
 * cURL rather than file_get_contents: shared hosts routinely disable
 * allow_url_fopen, and the failure when they do is a warning and `false`, which
 * reads downstream as "Google said no" rather than "this server cannot make
 * outbound requests at all".
 */
function mpc_google_post(string $url, array $fields): string
{
    if (! function_exists('curl_init')) {
        throw new RuntimeException('cURL is not available; cannot reach Google.');
    }

    $ch = curl_init($url);
    curl_setopt_array($ch, [
        CURLOPT_POST           => true,
        CURLOPT_POSTFIELDS     => http_build_query($fields),
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_TIMEOUT        => 15,

        // Both on, explicitly. They are the default, and they are also the
        // first thing switched off by someone debugging a certificate error at
        // 2am — at which point this exchange, which carries the client secret,
        // would accept any server claiming to be Google.
        CURLOPT_SSL_VERIFYPEER => true,
        CURLOPT_SSL_VERIFYHOST => 2,
    ]);

    $body   = curl_exec($ch);
    $errno  = curl_errno($ch);
    $error  = curl_error($ch);
    $status = (int) curl_getinfo($ch, CURLINFO_HTTP_CODE);
    curl_close($ch);

    if ($errno !== 0 || ! is_string($body)) {
        throw new RuntimeException("Could not reach Google ($errno): $error");
    }

    if ($status !== 200) {
        // Google puts the real reason in the body — redirect_uri_mismatch and
        // invalid_client are both common during setup and both look identical
        // from the outside. Keep it for the log; the visitor never sees it.
        throw new RuntimeException("Google returned HTTP $status: " . mb_substr($body, 0, 300));
    }

    return $body;
}


// ---------------------------------------------------------------------------
// Turning a Google identity into a user row
// ---------------------------------------------------------------------------

/**
 * Finds or creates the student behind a set of Google claims.
 *
 * The matching rules, in order, and each one is a decision rather than a
 * detail:
 *
 *   1. A row in social_accounts for (google, sub) — the only identifier Google
 *      promises is stable. An email address is not: people change theirs, and
 *      the address alone would then either lock them out or, worse, hand their
 *      account to whoever inherits the address.
 *
 *   2. Failing that, a users row with the same email, ONLY when both sides say
 *      that email is verified. This is what lets a student the office already
 *      recorded sign in without becoming a second person in the database.
 *
 *   3. Failing that, a new student row.
 *
 * Staff and admin accounts are refused at step 2 and never reached at step 1,
 * because step 1 can only match a link this function refused to create. See the
 * header for why.
 *
 * @return array{0:?int,1:?string} [user id, error message for the visitor]
 */
function mpc_google_link_user(array $claims): array
{
    $db = mpc_db();

    $stmt = $db->prepare(
        "SELECT u.id, u.role, u.status
           FROM social_accounts s
           JOIN users u ON u.id = s.user_id
          WHERE s.provider = 'google' AND s.provider_user_id = ?"
    );
    $stmt->execute([$claims['sub']]);
    $linked = $stmt->fetch();

    if ($linked) {
        if ($linked['status'] !== 'active') {
            return [null, 'That account is suspended. Please call the office.'];
        }
        if (in_array($linked['role'], ['staff', 'admin'], true)) {
            return [null, mpc_google_staff_message()];
        }

        return [(int) $linked['id'], null];
    }

    $email    = $claims['email'];
    $verified = $claims['email_verified'];

    if ($email !== null && $verified) {
        $stmt = $db->prepare(
            "SELECT id, role, status, email_verified_at FROM users WHERE email = ?"
        );
        $stmt->execute([$email]);
        $existing = $stmt->fetch();

        if ($existing) {
            if (in_array($existing['role'], ['staff', 'admin'], true)) {
                return [null, mpc_google_staff_message()];
            }
            if ($existing['status'] !== 'active') {
                return [null, 'That account is suspended. Please call the office.'];
            }

            // An unverified existing row is NOT linked automatically. It was
            // created by someone typing an address — at the enrolment desk, or
            // into a form — and nobody has proved they own it. Linking here
            // would let anyone who can register that address at Google walk
            // into the account it names. It needs a human at the office to
            // confirm, and there is no screen for that yet, so it is refused
            // rather than guessed.
            if ($existing['email_verified_at'] === null) {
                return [null,
                    'An account already uses that email address, but it has not been '
                    . 'confirmed yet. Please call the office on +252 770 51 90 98 and '
                    . 'we will connect it for you.'];
            }

            mpc_google_insert_link((int) $existing['id'], $claims);

            return [(int) $existing['id'], null];
        }
    }

    // A brand new student. Role and status are written explicitly rather than
    // left to the column defaults, so that a change to those defaults later
    // cannot quietly start creating something other than an active student
    // from a public, unauthenticated endpoint.
    $insert = $db->prepare(
        "INSERT INTO users (full_name, email, email_verified_at, role, status, avatar_url)
         VALUES (?, ?, ?, 'student', 'active', ?)"
    );
    $insert->execute([
        mb_substr(trim($claims['name'] ?? '') ?: ($email ?? 'Student'), 0, 160),

        // Only store the address when Google vouches for it. An unverified one
        // would take the UNIQUE slot on users.email and block the real owner
        // from ever registering it.
        $verified ? $email : null,
        $verified ? date('Y-m-d H:i:s') : null,
        $claims['picture'] !== null ? mb_substr($claims['picture'], 0, 500) : null,
    ]);

    $userId = (int) $db->lastInsertId();
    mpc_google_insert_link($userId, $claims);

    return [$userId, null];
}

/** Records the provider link. Separate function because it happens from two
 *  places above and both must write the same row. */
function mpc_google_insert_link(int $userId, array $claims): void
{
    $stmt = mpc_db()->prepare(
        "INSERT INTO social_accounts
                (user_id, provider, provider_user_id, provider_email, email_verified)
         VALUES (?, 'google', ?, ?, ?)"
    );
    $stmt->execute([
        $userId,
        $claims['sub'],
        $claims['email'] !== null ? mb_substr($claims['email'], 0, 190) : null,
        $claims['email_verified'] ? 1 : 0,
    ]);
}

/** The one message staff see, in one place, so the two call sites cannot drift
 *  into saying different things about the same rule. */
function mpc_google_staff_message(): string
{
    return 'That address belongs to an MPC staff account. Staff sign in with a '
         . 'password at the office system, not with Google.';
}
